# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'gs-spring-boot-docker'
  tag: '$(Build.BuildId)'


steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
      repository: $(imageName)
      dockerfile: '$(Build.SourcesDirectory)/complete/Dockerfile'
      command: build